include:
  # Left side (Central)
  - board: xiao_ble
    shield: corne_xiao_v2_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_xiao_v2_left_studio

  # Right side (Peripheral)
  - board: xiao_ble
    shield: corne_xiao_v2_right
    artifact-name: corne_xiao_v2_right_rgb
